Coq small fixes
cryspen/hax pull request #1108
Opened 2024-11-11 15:55 UTC by cmester0

2024-11-19 11:43 UTC, cmester0 commented on test-harness/src/snapshots/toolchain__assert into-coq.snap
> +
Replace with core lib.

2024-11-19 11:43 UTC, cmester0 commented on test-harness/src/snapshots/toolchain__assert into-coq.snap
> +-R ./ TODO
Add name of create instead of TODO.

2024-11-19 11:43 UTC, cmester0 commented on examples/coverage/src/test_closures.rs
> +// }
Support closures.

2024-11-28 13:00 UTC, W95Psp commented
Let's look at that together to chat about CI, and merge

2024-11-28 13:48 UTC, W95Psp commented
Lasse and I are looking at that PR right now

2024-11-28 17:41 UTC, cmester0 commented on .github/workflows/extract_and_run_coq.yml
> +      #     done
TODO: Run Coq on (working) snapshot files. Still have to get full coverage.

2024-11-28 18:13 UTC, cmester0 commented
@W95Psp This should work now. Seems to be an issue with fstar snapshots with regards to hashes for the `install & test` CI job, and some `cd` issues in the `Extract and Run - Coq` job.

2025-01-23 12:43 UTC, franziskuskiefer commented
@W95Psp please have a look at this.

2025-02-06 17:01 UTC, cmester0 commented on examples/coverage/default.nix
> +        cd proofs/coq/extraction
Does the `cd` issue originate from here? Does it fail to generate something when running `cargo hax` here?

2025-03-04 16:52 UTC, cmester0 commented
It would be good to get this merged, the tests are nice, however, if we do not want to fix the Nix setup now, I can remove that part. Some of the features in this PR are related to the issues Andrei Listochkin is experiencing with the Coq backend.

2025-03-05 07:55 UTC, W95Psp commented
I'm looking into it

2025-03-05 13:11 UTC, W95Psp commented
@cmester0 I merged main and fixed a few things.
I'm not sure everything is right though, can you look at the changes?

2025-03-13 14:08 UTC, cmester0 commented on engine/lib/concrete_ident/concrete_ident.ml
>            prefix "f" (dstr n)
It seems the update of how names are rendered broke the Coq naming scheme, since the trait name needs to be prepended. Changing this to 
```ocaml
      | `AssociatedItem
          ((`Type n | `Const n | `Fn n), (`Impl (_, `Trait, _))) ->
        prefix "f" (dstr n)
      | `AssociatedItem
          ((`Type n | `Const n | `Fn n), (`Trait (a, _))) ->
          Concat (dstr a, prefix "f" (dstr n))
```
Only half fixes the issue, as I still need to prefix the impl function name.

2025-04-10 14:04 UTC, cmester0 commented
@W95Psp it seems the changes on main broke the Coq naming scheme, as the trait name no longer is prepended (required for uniqueness of names). Should I add some more parameters to the naming engine?

2025-04-23 10:06 UTC, W95Psp commented
> @W95Psp it seems the changes on main broke the Coq naming scheme, as the trait name no longer is prepended (required for uniqueness of names). Should I add some more parameters to the naming engine?

Maxime just made a PR which is somehow related: https://github.com/cryspen/hax/pull/1416.
If I understand correctly, for Coq, you always want a prefix.
Thus you need to add a parameter (say "associated_item_trait_prefixed: bool") defaulting to false in NAME_POLICY (https://github.com/cryspen/hax/blob/acccf6a98661cd05a2d586c39d1db86807cf5eb1/engine/lib/concrete_ident/concrete_ident_render_sig.ml#L5), and change the behavior in concrete_ident.ml similarly to what #1416 does.

2025-04-30 11:23 UTC, cmester0 commented on examples/coverage/default.nix
> +        cd proofs/coq/extraction
Seemed to be an issue with having to do `cd ../../../../` to get back to the start directory after running the script.

2025-04-30 14:07 UTC, W95Psp requested changes
Thanks for the PR, I have some remarks, hopefully that should not be too much of a big deal to fix

2025-04-30 14:07 UTC, W95Psp commented on examples/coverage/Cargo.toml
> +[package]
This crate contains a lot of commented code: shall we clean this up?
Also, can you add a README here to explain what this example is about?

2025-04-30 14:07 UTC, W95Psp commented on examples/coverage/Cargo.toml
> +[package]
Isn't this redundant with `tests/`?

2025-04-30 14:07 UTC, W95Psp commented on examples/coverage/default.nix
> +        # gnused
drop?

2025-04-30 14:07 UTC, W95Psp commented on examples/coverage/default.nix
> +	cd ../../../../../
Running `cargo hax into coq` in the `extraction` will work fine here

Also, you could just wrap in a sub shell so that you don't need to bother with wierd `cd ..`s

```suggestion
        (
          cd examples/coverage/proofs/coq/extraction/
          cargo hax into coq
	  echo -e "-R ${coqGeneratedCore}/lib/coq/user-contrib/Core Core\n$(cat _CoqProject)" > _CoqProject
	  coq_makefile -f _CoqProject -o Makefile
	  make
	)
```

2025-04-30 14:07 UTC, W95Psp commented on flake.nix
> +          };
I think we should have the `coq-coverage-example` included in the `checks.examples` derivation, don't you think?
I don't see why this one example should be exposed specifically here

2025-05-01 14:29 UTC, cmester0 commented on examples/coverage/Cargo.toml
> +[package]
Possibly, this could be moved into some of the tests. We will probably want some tests for the semantics, and not just testing cases of code generation.

2025-05-01 15:23 UTC, cmester0 commented on flake.nix
> +          };
Yes, there should not be a big difference from the other examples. My only worry is that it becomes quite a large job, if you want to run all of them in a single runner.

2025-05-01 16:12 UTC, cmester0 commented
This somewhat works now. We can do some follow up PRs for structuring things or adding more tests.

2025-05-05 07:35 UTC, karthikbhargavan approved these changes
As long as it passes CI, let's get this in.

2025-05-05 07:36 UTC, karthikbhargavan commented on .github/workflows/extract_and_run_coq.yml
> +      #     done
Done? If so, resolve.

2025-05-05 07:36 UTC, karthikbhargavan commented on examples/coverage/src/test_closures.rs
> +// }
Maybe add an issue for this?

2025-05-05 07:37 UTC, karthikbhargavan commented on test-harness/src/snapshots/toolchain__assert into-coq.snap
> +-R ./ TODO
Fix this?

2025-05-06 10:15 UTC, cmester0 commented on examples/coverage/src/test_closures.rs
> +// }
Added #1441.

2025-05-06 10:17 UTC, cmester0 commented on engine/lib/concrete_ident/concrete_ident.ml
> +      | `AssociatedItem ((`Type n | `Const n | `Fn n), `Trait (a, _)) ->
Added something for impls.

2025-05-06 10:53 UTC, merged