Hax auto syntax
cryspen/hax pull request #986
Opened 2024-10-10 14:58 UTC by cmester0

Generate the accepted Hax syntax using a shallow printer.

2024-10-10 14:59 UTC, cmester0 commented
Alternative to #975

2024-10-12 22:45 UTC, cmester0 commented
2223%22%20width%3D%2268%22%20height%3D%2232%22%20rx%3D%2210%22%2F%3E%3Crect%20x%3D%2289%22%20y%3D%2221%22%20width%3D%2268%22%20height%3D%2232%22%20class%3D%22terminal%22%20rx%3D%2210%22%2F%3E%3Ctext%20class%3D%22terminal%22%20x%3D%2299%22%20y%3D%2241%22%3E%20string%20%3C%2Ftext%3E%3Crect%20x%3D%22179%22%20y%3D%2223%22%20width%3D%2220%22%20height%3D%2232%22%20rx%3D%2210%22%2F%3E%3Crect%20x%3D%22177%22%20y%3D%2221%22%20width%3D%2220%22%20height%3D%2232%22%20class%3D%22terminal%22%20rx%3D%2210%22%2F%3E%3Ctext%20class%3D%22terminal%22%20x%3D%22187%22%20y%3D%2241%22%2F%3E%3Crect%20x%3D%2251%22%20y%3D%2267%22%20width%3D%2224%22%20height%3D%2232%22%20rx%3D%2210%22%2F%3E%3Crect%20x%3D%2249%22%20y%3D%2265%22%20width%3D%2224%22%20height%3D%2232%22%20class%3D%22terminal%22%20rx%3D%2210%22%2F%3E%3Ctext%20class%3D%22terminal%22%20x%3D%2259%22%20y%3D%2285%22%3E%27%3C%2Ftext%3E%3Crect%20x%3D%2295%22%20y%3D%2267%22%20width%3D%2246%22%20height%3D%2232%22%2F%3E%3Crect%20x%3D%2293%22%20y%3D%2265%22%20width%3D%2246%22%20height%3D%2232%22%20class%3D%22nonterminal%22%2F%3E%3Ctext%20class%3D%22nonterminal%22%20x%3D%22103%22%20y%3D%2285%22%3Echar%3C%2Ftext%3E%3Crect%20x%3D%22161%22%20y%3D%2267%22%20width%3D%2224%22%20height%3D%2232%22%20rx%3D%2210%22%2F%3E%3Crect%20x%3D%22159%22%20y%3D%2265%22%20width%3D%2224%22%20height%3D%2232%22%20class%3D%22terminal%22%20rx%3D%2210%22%2F%3E%3Ctext%20class%3D%22terminal%22%20x%3D%22169%22%20y%3D%2285%22%3E%27%3C%2Ftext%3E%3Crect%20x%3D%2251%22%20y%3D%22111%22%20width%3D%2236%22%20height%3D%2232%22%2F%3E%3Crect%20x%3D%2249%22%20y%3D%22109%22%20width%3D%2236%22%20height%3D%2232%22%20class%3D%22nonterminal%22%2F%3E%3Ctext%20class%3D%22nonterminal%22%20x%3D%2259%22%20y%3D%22129%22%3Eint%3C%2Ftext%3E%3Crect%20x%3D%2251%22%20y%3D%22155%22%20width%3D%2248%22%20height%3D%2232%22%2F%3E%3Crect%20x%3D%2249%22%20y%3D%22153%22%20width%3D%2248%22%20height%3D%2232%22%20class%3D%22nonterminal%22%2F%3E%3Ctext%20class%3D%22nonterminal%22%20x%3D%2259%22%20y%3D%22173%22%3Efloat%3C%2Ftext%3E%3Crect%20x%3D%2251%22%20y%3D%22199%22%20width%3D%2248%22%20height%3D%2232%22%20rx%3D%2210%22%2F%3E%3Crect%20x%3D%2249%22%20y%3D%22197%22%20width%3D%2248%22%20height%3D%2232%22%20class%3D%22terminal%22%20rx%3D%2210%22%2F%3E%3Ctext%20class%3D%22terminal%22%20x%3D%2259%22%20y%3D%22217%22%3Etrue%3C%2Ftext%3E%3Crect%20x%3D%2251%22%20y%3D%22243%22%20width%3D%2252%22%20height%3D%2232%22%20rx%3D%2210%22%2F%3E%3Crect%20x%3D%2249%22%20y%3D%22241%22%20width%3D%2252%22%20height%3D%2232%22%20class%3D%22terminal%22%20rx%3D%2210%22%2F%3E%3Ctext%20class%3D%22terminal%22%20x%3D%2259%22%20y%3D%22261%22%3Efalse%3C%2Ftext%3E%3Cpath%20class%3D%22line%22%20d%3D%22m17%205%20h2%20m20%200%20h10%20m0%200%20h158%20m-188%200%20h20%20m168%200%20h20%20m-208%200%20q10%200%2010%2010%20m188%200%20q0%20-10%2010%20-10%20m-198%2010%20v12%20m188%200%20v-12%20m-188%2012%20q0%2010%2010%2010%20m168%200%20q10%200%2010%20-10%20m-178%2010%20h10%20m20%200%20h10%20m0%200%20h10%20m68%200%20h10%20m0%200%20h10%20m20%200%20h10%20m-178%20-10%20v20%20m188%200%20v-20%20m-188%2020%20v24%20m188%200%20v-24%20m-188%2024%20q0%2010%2010%2010%20m168%200%20q10%200%2010%20-10%20m-178%2010%20h10%20m24%200%20h10%20m0%200%20h10%20m46%200%20h10%20m0%200%20h10%20m24%200%20h10%20m0%200%20h14%20m-178%20-10%20v20%20m188%200%20v-20%20m-188%2020%20v24%20m188%200%20v-24%20m-188%2024%20q0%2010%2010%2010%20m168%200%20q10%200%2010%20-10%20m-178%2010%20h10%20m36%200%20h10%20m0%200%20h112%20m-178%20-10%20v20%20m188%200%20v-20%20m-188%2020%20v24%20m188%200%20v-24%20m-188%2024%20q0%2010%2010%2010%20m168%200%20q10%200%2010%20-10%20m-178%2010%20h10%20m48%200%20h10%20m0%200%20h100%20m-178%20-10%20v20%20m188%200%20v-20%20m-188%2020%20v24%20m188%200%20v-24%20m-188%2024%20q0%2010%2010%2010%20m168%200%20q10%200%2010%20-10%20m-178%2010%20h10%20m48%200%20h10%20m0%200%20h100%20m-178%20-10%20v20%20m188%200%20v-20%20m-188%2020%20v24%20m188%200%20v-24%20m-188%2024%20q0%2010%2010%2010%20m168%200%20q10%200%2010%20-10%20m-178%2010%20h10%20m52%200%20h10%20m0%200%20h96%20m23%20-252%20h-3%22%2F%3E%3Cpolygon%20points%3D%22237%205%20245%201%20245%209%22%2F%3E%3Cpolygon%20points%3D%22237%205%20229%201%20229%209%22%2F%3E%3C%2Fsvg%3E)

[RR]: https://www.bottlecaps.de/rr/ui

2024-10-12 22:46 UTC, cmester0 commented
I am currently generating the AST as EBNF, thus we can use tools like https://rr.red-dove.com/ui to render a diagram of the AST.

2024-10-17 06:16 UTC, franziskuskiefer commented
@cmester0 what does it take to get this in a reviewable state? The plan was to get this done this week.

2024-10-24 16:56 UTC, cmester0 commented
This should be mostly ready for review. Only missing description for some cases.

2024-10-29 11:02 UTC, cmester0 commented
Print EBNF formula as a command (not sure the setup is correct). Currently a full generic printer is implemented for this, however, we might be able to instrument e.g. a rust generic printer as a layered printer being able to print the EBNF formula.

2024-10-31 12:30 UTC, W95Psp requested changes
This should use the Rust printer, but instrumented towards EBNF printing

2025-01-23 12:40 UTC, franziskuskiefer commented
Closing this, please re-open @cmester0 if it's something you want to do.

2025-01-23 12:40 UTC, closed without merging